// Generates src/lib/us-map-paths.ts — the static state outlines + metro points the Regions
// map draws. Run once; the output is committed so the site carries no map dependencies.
//
//   cd <any scratch dir> && npm i us-atlas@3 topojson-client@3 d3-geo@3
//   node <repo>/web/scripts/gen-us-map.mjs <scratch dir>/node_modules <repo>/web/src/lib/us-map-paths.ts
//
// Add a metro to METROS and rerun when a new city region needs a dot.

import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';

const [modulesDir, outFile] = process.argv.slice(2);
if (!modulesDir || !outFile) throw new Error('usage: gen-us-map.mjs <node_modules dir> <out .ts file>');
const require = createRequire(path.join(modulesDir, 'x.js'));
const { feature } = require('topojson-client');
const { geoPath, geoAlbersUsa } = require('d3-geo');

// states-albers-10m is pre-projected to 975×610 with geoAlbersUsa().scale(1300).translate([487.5, 305]).
const topo = JSON.parse(readFileSync(path.join(modulesDir, 'us-atlas/states-albers-10m.json'), 'utf8'));
const states = feature(topo, topo.objects.states).features;
const pathGen = geoPath().digits(1);
const projection = geoAlbersUsa().scale(1300).translate([487.5, 305]);

const FIPS = {
  '01': 'AL', '02': 'AK', '04': 'AZ', '05': 'AR', '06': 'CA', '08': 'CO', '09': 'CT', '10': 'DE', '11': 'DC',
  '12': 'FL', '13': 'GA', '15': 'HI', '16': 'ID', '17': 'IL', '18': 'IN', '19': 'IA', '20': 'KS', '21': 'KY',
  '22': 'LA', '23': 'ME', '24': 'MD', '25': 'MA', '26': 'MI', '27': 'MN', '28': 'MS', '29': 'MO', '30': 'MT',
  '31': 'NE', '32': 'NV', '33': 'NH', '34': 'NJ', '35': 'NM', '36': 'NY', '37': 'NC', '38': 'ND', '39': 'OH',
  '40': 'OK', '41': 'OR', '42': 'PA', '44': 'RI', '45': 'SC', '46': 'SD', '47': 'TN', '48': 'TX', '49': 'UT',
  '50': 'VT', '51': 'VA', '53': 'WA', '54': 'WV', '55': 'WI', '56': 'WY',
};

/** [lon, lat] — a representative point for each metro region. */
const METROS = {
  Austin: [-97.74, 30.27],
  Dallas: [-96.8, 32.78],
  Houston: [-95.37, 29.76],
  Jacksonville: [-81.66, 30.33],
  Miami: [-80.19, 25.76],
  Orlando: [-81.38, 28.54],
  Tampa: [-82.46, 27.95],
  'North Georgia': [-84.3, 34.0],
  'South Georgia': [-83.5, 31.45],
};

const stateLines = states
  .map((f) => {
    const abbr = FIPS[f.id];
    if (!abbr) return null;
    return `  ${abbr}: { name: ${JSON.stringify(f.properties.name)}, d: ${JSON.stringify(pathGen(f))} },`;
  })
  .filter((l) => l !== null)
  .sort();

const metroLines = Object.entries(METROS).map(([name, lonLat]) => {
  const p = projection(lonLat);
  if (!p) throw new Error(`${name} projects outside the map`);
  return `  ${JSON.stringify(name)}: { x: ${p[0].toFixed(1)}, y: ${p[1].toFixed(1)} },`;
});

const out = `// GENERATED by scripts/gen-us-map.mjs — do not edit by hand.
// US state outlines (us-atlas states-albers-10m, 975×610 viewBox) and projected metro points.

export const US_MAP_VIEWBOX = '0 0 975 610';

export interface StateShape {
  name: string;
  d: string;
}

export const US_STATE_PATHS: Record<string, StateShape> = {
${stateLines.join('\n')}
};

export const METRO_POINTS: Record<string, { x: number; y: number }> = {
${metroLines.join('\n')}
};
`;

writeFileSync(outFile, out);
console.log(`wrote ${outFile} (${(out.length / 1024).toFixed(0)} KB, ${stateLines.length} states)`);
